dependencies:
  - name: opencv-python
    version: ">=4.8.0"
  - name: numpy
    version: ">=1.24.0"
  - name: pandas
    version: ">=2.0.0"
  - name: psycopg2-binary
    version: ">=2.9.0"
  - name: python-dotenv
    version: ">=1.0.0"
  - name: RPi.GPIO
    version: ">=0.7.0"
  - name: dht11
    version: ">=0.0.1"
  - name: python-dateutil
    version: ">=2.8.2"
  - name: pillow
    version: ">=10.0.0"
  - name: libcamera
    version: ">=0.0.1"
  - name: typing-extensions
    version: ">=4.7.0"